version: "3"

networks:

  default:
    external: false
  proxy:
    external: true

services:

  elasticsearch:
    image: elasticsearch:5.1.2-alpine
    networks:
      - default
    deploy:
      resources:
        reservations:
          memory: 250M

  logstash:
    image: vfarcic/logstash-devops21
    networks:
      - default
    environment:
      - LOGSPOUT=ignore
    deploy:
      resources:
        reservations:
          memory: 100M

  kibana:
    image: kibana:5.1.2
    networks:
      - default
      - proxy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      resources:
        reservations:
          memory: 50M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/app,/elasticsearch,/api,/ui,/bundles,/plugins
        - com.df.port=5601

  logspout:
    image: gliderlabs/logspout
    networks:
      - default
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://logstash:51415
    deploy:
      mode: global
