version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:rc
    networks:
     - proxy
    ports:
      - 80:80
      - 443:443
      - 22:22
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=git.nibor.me,docker.nibor.me
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=443