version: '3'

services:

  main:
    image: jenkins/jenkins:${TAG:-lts-alpine}
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    deploy:
      resources:
        reservations:
          memory: 300M